In [1]:
#!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2,3,4],[1,2,3,4]])
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [8]:
a.ndim # Dimension

1

In [9]:
b.ndim

2

In [10]:
a.shape  # shape

(4,)

In [11]:
b.shape

(2, 4)

In [13]:
b.dtype  # Datatype

dtype('int32')

In [14]:
a.itemsize

4

In [15]:
b.itemsize

4

In [16]:
a.nbytes

16

In [17]:
b.nbytes

32

In [19]:
c = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
c

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [20]:
c[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
c[:,2]

array([3, 3])

In [24]:
# c[1,1]
# c[1,3]
c[1,2]

3

In [25]:
d = np.array([[[1,2],[2,3],[3,4],[4,5]]])
d

array([[[1, 2],
        [2, 3],
        [3, 4],
        [4, 5]]])

In [26]:
d.ndim

3

In [31]:
# s = np.zeros((3,2)) # zero's 
s = np.ones((2,3))   # one's
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
d = np.full((2,3),99)
d

array([[99, 99, 99],
       [99, 99, 99]])

In [37]:
f = np.random.rand(4,2)  # Genrates a random values between given 2 numbers.
f

array([[0.50353026, 0.88682416],
       [0.84665567, 0.13313729],
       [0.70078071, 0.32936689],
       [0.902069  , 0.51865933]])

In [39]:
c = np.identity(5) # identity matrix
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
t = np.array([1,2,3,4])
b = t.copy()
b[0] = 100
# b
a

array([1, 2, 3, 4])

In [47]:
t = np.array([1,2,3,4])


In [49]:
# t+2
# t-2
# t*2
# t/2

array([3, 4, 5, 6])